version: "3.9"

services:
  configserver:
    build: ./configserver
    ports:
      - "8888:8888"
    restart: always
    networks:
      - fitness-net

  eureka:
    build: ./eureka
    ports:
      - "8761:8761"
    depends_on:
      - configserver
    networks:
      - fitness-net

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - fitness-net

  userservice:
    build: ./userservice
    ports:
      - "8081:8081"
    depends_on:
      - configserver
      - eureka
      - rabbitmq
    networks:
      - fitness-net

  activityservice:
    build: ./activityservice
    ports:
      - "8082:8082"
    depends_on:
      - configserver
      - eureka
      - rabbitmq
    networks:
      - fitness-net

  aiservice:
    build: ./aiservice
    ports:
      - "8083:8083"
    depends_on:
      - configserver
      - eureka
      - rabbitmq
    networks:
      - fitness-net

  gateway:
    build: ./gateway
    ports:
      - "8080:8080"
    depends_on:
      - eureka
    networks:
      - fitness-net

networks:
  fitness-net:
    driver: bridge
