version: '3.8'

services:
  eureka:
    image: vikass02/eureka:latest
    container_name: eureka
    ports:
      - "8761:8761"
    restart: always

  configserver:
    image: vikass02/configserver:latest
    container_name: configserver
    depends_on:
      - eureka
    ports:
      - "8888:8888"
    restart: always

  gateway:
    image: vikass02/gateway:latest
    container_name: gateway
    depends_on:
      - eureka
      - configserver
    ports:
      - "8080:8080"
    restart: always

  userservice:
    image: vikass02/userservice:latest
    container_name: userservice
    depends_on:
      - eureka
    ports:
      - "8081:8081"
    restart: always

  activityservice:
    image: vikass02/activityservice:latest
    container_name: activityservice
    ports:
      - "8082:8082"
    restart: always

  aiservice:
    image: vikass02/aiservice:latest
    container_name: aiservice
    ports:
      - "8083:8083"
    restart: always

networks:
  default:
    name: fitness-net
